apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    test.speedscale.com/scenarioid: a4493e02-b954-474b-aaf9-ff9bd1b04e79
    test.speedscale.com/testconfigid: standard
    test.speedscale.com/cleanup: "true"
    test.speedscale.com/tag: COMMIT_HASH
    sidecar.speedscale.com/inject: "true"
